FROM python:3.11

COPY ./api/requirements.txt /requirements.txt
RUN pip install --no-cache-dir --upgrade -r /requirements.txt

WORKDIR /app

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80" ]
